name: Run daily script and Save Data

on:
  schedule:
    - cron: "30 12 * * *"   # 09:30 Argentina
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas matplotlib seaborn xlsxwriter

      - name: Run script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: |
          python bigmac.py

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Añadir cambios en el CSV y en la carpeta docs (web + imágenes)
          git add mcdonalds_precios.csv docs/
          
          if git diff --staged --quiet; then
            echo "No hay cambios para subir."
          else
            git commit -m "Update prices and Dashboard (daily scan)"
            git push
          fi
          
